version: "3.7"

networks:
  app_net:
    driver: bridge


services:
  database:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_NAME: $DB_NAME
      POSTGRES_HOST: $DB_HOST
    ports:
      - '5432:5432'
    networks:

      - app_net
  dev:
    build:
      context: .
      dockerfile: dockerfile
    container_name: booking-app-dev
  

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app_net
    depends_on:
      - database
 


 


volumes:
  node_modules:

